# Default Profile
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false

---
# Docker Profile
spring:
  config:
    activate:
      on-profile: docker
    import: optional:configserver:http://operis-configuration-server:8888

eureka:
  instance:
    hostname: operis-servicediscovery # Matches the container name/alias in docker-compose
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false