spring:
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:9000/realms/operis
            jwk-set-uri: http://localhost:9000/realms/operis/protocol/openid-connect/certs
    data:
      redis:
        host: localhost
        port: 6378
        password: password

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - busrefresh
          - prometheus
          - metrics
          - circuitbreakers
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    circuitbreakers:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    circuitbreakers:
      enabled: true
  tracing:
    export:
      otlp:
        enabled: true
      enabled: true
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
          transport: http
  otlp:
    metrics:
      export:
        enabled: false




