spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://euc1.auth.ac/auth/realms/operis

  data:
    redis:
      host: redis
      port: 6379
      password: password

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://postgres-operis-task:5432/operis_task_db

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: operis
    password: password

management:
  server:
    port: 9095
  endpoints:
    web:
      exposure:
        include:
          - health
          - busrefresh
          - prometheus
          - metrics
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  tracing:
    export:
      otlp:
        enabled: true
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://tempo:4318/v1/traces
          transport: http
  otlp:
    metrics:
      export:
        enabled: false

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://operis-discovery-service:8761/eureka