server:
  port: 0

spring:
  application:
    name: operis-notification-service

  config:
    import: optional:configserver:/

  cloud:
    config:
      discovery:
        enabled: true
        service-id: operis-configuration-server

  mail:
    host: localhost
    protocol: smtp
    username: ""
    password: ""
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

operis:
  frontend-url: http://localhost:4200/
  notifications:
    email:
      from: no-reply@operis.com

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka