spring:
  mail:
    host: localhost
    protocol: smtp
    username: ""
    password: ""
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
            
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/realms/operis
  
  rabbitmq:
    host: localhost
    port: 5672
    username: operis
    password: password

management:
  server:
    port: 9093
  endpoints:
    web:
      exposure:
        include:
          - health
          - busrefresh
          - prometheus
          - metrics
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  tracing:
    export:
      otlp:
        enabled: true
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
          transport: http
  otlp:
    metrics:
      export:
        enabled: false

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7

rabbitmq:
  exchange:
    name: project.invitation.exchange
  routing:
    key: project.invite
  queue:
    notification-service: project.invitation.notification.queue

operis:
  frontend-url: http://localhost:4200/
  notifications:
    email:
      from: no-reply@operis.com

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka