spring:
    gateway:
      server:
        webflux:
          routes:
            - id: operis-project-service
              uri: lb://operis-project-service
              predicates:
                - Path=/api/v1/projects/**, /api/v1/project-invitations/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: projectServiceCB
                    fallbackUri: forward:/fallback
            - id: operis-user-service
              uri: lb://operis-user-service
              predicates:
                - name: Path
                  args:
                    pattern: /api/v1/users/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: userServiceCB
                    fallbackUri: forward:/fallback
            - id: operis-cta-service
              uri: lb://operis-cta-service
              predicates:
                - name: Path
                  args:
                    pattern: /api/v1/call-to-actions/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: ctaServiceCB
                    fallbackUri: forward:/fallback
            - id: operis-task-service
              uri: lb://operis-task-service
              predicates:
                - name: Path
                  args:
                    pattern: /api/v1/tasks/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: taskServiceCB
                    fallbackUri: forward:/fallback
            - id: operis-subscription-service
              uri: lb://operis-subscription-service
              predicates:
                - name: Path
                  args:
                    pattern: /api/v1/subscriptions/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: subscriptionServiceCB
                    fallbackUri: forward:/fallback
          default-filters:
            - name: Retry
              args:
                retries: 3
                methods: GET
                backoff:
                  firstBackoff: "200ms"
                  maxBackoff: "2s"
                  factor: 2
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@ipKeyResolver}"
          httpclient:
            connect-timeout: 10000
            response-timeout: 5s
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://keycloak:8080/realms/operis
    data:
      redis:
        host: redis
        port: 6379
        password: password

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://operis-discovery-service:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - busrefresh
          - prometheus
          - metrics
          - circuitbreakers
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    circuitbreakers:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    circuitbreakers:
      enabled: true
  tracing:
    export:
      otlp:
        enabled: true
      enabled: true
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://tempo:4318/v1/traces
          transport: http
  otlp:
    metrics:
      export:
        enabled: false

resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 10s
    instances:
      subscriptionServiceCB:
        base-config: default
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 10
        minimum-number-of-calls: 5
        sliding-window-type: count_based
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      projectServiceCB:
        base-config: default
      userServiceCB:
        base-config: default
      ctaServiceCB:
        base-config: default
      taskServiceCB:
        base-config: default
      subscriptionServiceCB:
        base-config: default
        slow-call-duration-threshold:
          seconds: 10




