spring:
  devtools:
    restart:
      enabled: false  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://euc1.auth.ac/auth/realms/operis
          
  data:
    redis:
      host: redis
      port: 6379
      password: password

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://postgres-operis-project:5432/operis_project_db

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: operis
    password: password

eureka:
  client:
    serviceUrl:
      defaultZone: http://operis-discovery-service:8761/eureka

management:
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://tempo:4318/v1/traces
          transport: http
