spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/realms/operis

  rabbitmq:
    host: localhost
    port: 5672
    username: operis
    password: password

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:54324/operis_task_db

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  server:
    port: 9095
  endpoints:
    web:
      exposure:
        include:
          - health
          - busrefresh
          - prometheus
          - metrics
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  tracing:
    export:
      otlp:
        enabled: true
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
          transport: http
  otlp:
    metrics:
      export:
        enabled: false

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
