spring:
  mail:
    host: maildev
    protocol: smtp
    username: ""
    password: ""
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
            
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8000/realms/operis
  
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: operis
    password: password

management:
  server:
    port: 9093
  endpoints:
    web:
      exposure:
        include:
          - health
          - busrefresh
          - prometheus
          - metrics
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  tracing:
    export:
      otlp:
        enabled: true
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://tempo:4318/v1/traces
          transport: http
  otlp:
    metrics:
      export:
        enabled: false


operis:
  frontend-url: http://operis-angular-ui:80/
  notifications:
    email:
      from: no-reply@operis.com

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://operis-discovery-service:8761/eureka